# Generated by Django 5.2b1 on 2025-03-18 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation_type',
        ),
        migrations.AddField(
            model_name='donation',
            name='frequency',
            field=models.CharField(choices=[('one-time', 'One-Time'), ('recurring', 'Recurring')], default='one-time', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
