# Generated by Django 5.2b1 on 2025-03-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='member_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
