# Generated by Django 5.2b1 on 2025-03-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventregistration_member_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='member_count',
        ),
    ]
