# Generated by Django 5.2b1 on 2025-03-13 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventregistration_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='volunteers',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='participant_name',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='volunteer',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Reference to the logged-in user who registered (if any).', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='member_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of people attending'),
        ),
    ]
