# Generated by Django 5.2b1 on 2025-03-18 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_volunteers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='member_count',
            field=models.PositiveIntegerField(default=1, help_text='Number of attendees'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
