# Generated by Django 5.2b1 on 2025-03-18 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
