# Generated by Django 5.2b1 on 2025-03-18 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_delete_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_closed',
        ),
    ]
