# Generated by Django 5.2b1 on 2025-03-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('total_donated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_events', models.PositiveIntegerField(default=0)),
                ('total_event_registrations', models.PositiveIntegerField(default=0)),
                ('total_volunteers', models.PositiveIntegerField(default=0)),
                ('total_volunteer_assignments', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
