# Generated by Django 5.2b1 on 2025-03-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('volunteer', 'Volunteer'), ('admin', 'Administrator')], default='donor', max_length=15),
        ),
    ]
